name: Fetch AWS Secrets Using OIDC

on:
  workflow_dispatch:  # This enables manual trigger from the GitHub interface

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS OIDC authentication
      - name: Set up AWS OIDC authentication
        id: aws-oidc
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::985539771845:role/GITHUB-ACTIONS/INFRA/PROD/GITHUB-ACTIONS-TEST  # Replace with your IAM Role ARN
          role-session-name: GitHubActionsSession  # A session name for temporary credentials
          aws-region: ap-south-1  # Required region based on your secret ARN (ap-south-1)

      # Step 3: Fetch secret from AWS Secrets Manager
      - name: Fetch secret from AWS Secrets Manager
        id: get_secret
        run: |
          SECRET_NAME="GITHUB-ACTIONS/INFRA/PROD/GITHUB-ACTIONS-TEST"  # Your secret name
          secret_value=$(aws secretsmanager get-secret-value --secret-id $SECRET_NAME --query SecretString --output text)
          echo "SECRET_VALUE=$secret_value" >> $GITHUB_ENV  # Store the secret as an environment variable

      # Step 4: Use the secret (for testing or deployment)
      - name: Display fetched secret (be cautious in production)
        run: |
          echo "Fetched secret: ${{ env.SECRET_VALUE }}"
